webapp/cocktails/models.py
from webapp.db import db


class Cocktails(db.Model):
    """Создает модель коктейля в БД
    """

    id = db.Column(db.Integer, unique=True, primary_key=True)
    title = db.Column(db.String, unique=True)
    image = db.Column(db.String, unique=True)
    cocktail_tag = db.relationship('Tags', backref='cocktails', lazy='joined')
    cocktail_recipe = db.relationship('Recipe', backref='cocktails', lazy='joined')
    cocktail_ingredients = db.relationship('Ingredients', backref='cocktails', lazy='joined')
    cocktail_tools = db.relationship('Tools', backref='cocktails', lazy='joined')

    def __repr__(self):
        return f"Coctails {self.id} {self.title}"


class Tags(db.Model):
    """Создает модель тегов коктейля
    """

    id = db.Column(db.Integer, unique=True, primary_key=True)
    tags = db.Column(db.String)
    cocktail_id = db.Column(
        db.Integer,
        db.ForeignKey('cocktails.id', ondelete='CASCADE'),
        index=True
    )

    def __repr__(self):
        return f"Tags {self.id}"


class Recipe(db.Model):
    """Создает модель рецепта коктейля
    """

    id = db.Column(db.Integer, unique=True, primary_key=True)
    recipe = db.Column(db.Text)
    cocktail_id = db.Column(
        db.Integer,
        db.ForeignKey('cocktails.id', ondelete='CASCADE'),
        index=True
    )

    def __repr__(self):
        return f"Recipe {self.id} {self.cocktail_id}"


class Ingredients(db.Model):
    """Создает модель ингредиентов коктейля
    """

    id = db.Column(db.Integer, unique=True, primary_key=True)
    ingredient = db.Column(db.Text)
    amount = db.Column(db.Integer, nullable=True)
    unit = db.Column(db.String, nullable=True)
    cocktail_id = db.Column(
        db.Integer,
        db.ForeignKey('cocktails.id', ondelete='CASCADE'),
        index=True
    )

    def __repr__(self):
        return f"Ingredients {self.id} {self.cocktail_id}"


class Tools(db.Model):
    """Создает модель необходимой посуды для коктейля
    """

    id = db.Column(db.Integer, unique=True, primary_key=True)
    tool = db.Column(db.String)
    amount = db.Column(db.Integer, nullable=True)
    unit = db.Column(db.String, nullable=True)
    cocktail_id = db.Column(
        db.Integer,
        db.ForeignKey('cocktails.id', ondelete='CASCADE'),
        index=True
    )

    def __repr__(self):
        return f"Tools {self.id} {self.cocktail_id}"

webapp/cocktails/views.py
from flask import Blueprint, render_template, redirect, url_for
from sqlalchemy.sql.expression import func
from webapp.cocktails.models import Cocktails, Tags
from webapp.user.forms import SearchForm
from webapp import db


blueprint = Blueprint('cocktail', __name__)


@blueprint.route('/')
def index():
    page_title = 'Home-barman'
    cocktails = Cocktails.query.order_by(func.random()).limit(12).all()
    return render_template('index.html', page_title=page_title, cocktails=cocktails)


@blueprint.route('/recipe')
def recipe():
    return render_template('recipe.html')

@blueprint.route('/cocktail/<int:cocktail_id>')
def single_cocktail(cocktail_id):
    my_cocktail = Cocktails.query.filter(Cocktails.id == cocktail_id).first()
    return render_template('cocktails/single_cocktail.html', page_title=my_cocktail.title,
                            my_cocktail=my_cocktail)


@blueprint.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    cocktails = Cocktails.query
    if form.validate_on_submit():
        single_cocktail.searched = form.searched.data
        cocktails = cocktails.filter((Cocktails.tags.like('%' + single_cocktail.searched + '%') |
                                     (Cocktails.title.like('%' + single_cocktail.searched + '%'))))
        return render_template('cocktails/search.html', form=form,
                               searched=single_cocktail.searched, cocktails=cocktails)
    else:
        return redirect(url_for('cocktail.index'))

webapp/templates/cocktails/cocktails.html
{% block content %}
<div class="container text-center">
</div>
<div class="row">
  <div class="col-12 text-center mt-2"><h3>Коктейли</h3></div>
</div>
  <div class="row row-cols-1 row-cols-md-3 g-4 cocktail-grid">
    {% for cocktail in cocktails %}
    <div class="col">
      <div class="card h-100">
        <img class="cocktail-item-image" src="{{ cocktail.image }}" alt="{{ cocktail.title }}">
        <div class="card-body">
          <h5 class="card-title">{{ cocktail.title }}</h5>
          <p class="card-text">
            <ul>
                {% for tags in cocktail.cocktail_tag|reverse %} 
                <li class="tag"> {{ tags.tags }}</li>
                {% endfor %}
            </ul>
          </p>
        </div>
        <div class="card-footer">
          <a href="{{ url_for('cocktail.single_cocktail', cocktail_id=cocktail.id) }}" class="btn btn-primary">Рецепт</a>
        </div>
      </div>
    </div>
  
  {% endfor %}
</div>
{% endblock %}

webapp/templates/cocktails/search.html
{%extends 'base.html' %}

	<div class="container text-center">
	</div>
	<div class="row">
	  <div class="col-12 text-center mt-2"><h3>Вы искали: {{ searched }}</h3></div>
	</div>
	  <div class="row row-cols-1 row-cols-md-3 g-4 cocktail-grid">
		{% for cocktail in cocktails %}
		<div class="col">
		  <div class="card h-100">
			<img class="cocktail-item-image" src="{{ cocktail.image }}" alt="{{ cocktail.title }}">
			<div class="card-body">
			  <h5 class="card-title">{{ cocktail.title }}</h5>
			  <p class="card-text">{{ cocktail.tags }}</p>
			</div>
			<div class="card-footer">
			  <a href="{{ url_for('cocktail.cocktail', id=cocktail.id) }}" class="btn btn-primary">Рецепт</a>
			</div>
		  </div>
		</div>
	  
	  {% endfor %}
	</div>

webapp/templates/cocktails/single_cocktail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Home-barman</title>
</head>
<!-- Fixed navbar -->
      {% include 'menu.html' %}
<body>
  <br/>
  <div class="container">

<div class="container text-center">
</div>
<div class="row">
  <div class="col-12 text-center mt-2"><h3>{{ my_cocktail.title }}</h3></div>
</div>
  <div class="row row-cols-1 row-cols-md-3 g-4 cocktail-grid">
    <div class="col">
      <div class="card h-100">
        <img class="cocktail-item-image" src="{{ my_cocktail.image }}" alt="{{ my_cocktail.title }}">
        <div class="card-body">
            <ul>
            {% for tags in my_cocktail.cocktail_tag|reverse %} 
            <li class="tag"> {{ tags.tags }}</li>
            {% endfor %}
            </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="ingredient-tables">
    <table class="table">
        <tbody>
        <tr>
            <th colspan="3">Необходимые ингредиенты</th>
        </tr>
        {% for ingredients in my_cocktail.cocktail_ingredients %}
        <tr>
            <td class="name"> {{ ingredients.ingredient }} </td>
            <td class="amount"> {{ ingredients.amount }} </td>
            <td class="unit"> {{ ingredients.unit }} </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table">
        <tbody>
        <tr>
            <th colspan="3">Необходимые штучки</th>
        </tr>
        {% for tools in my_cocktail.cocktail_tools %}
        <tr>
            <td class="name"> {{ tools.tool }} </td>
            <td class="amount"> {{ tools.amount }} </td>
            <td class="unit"> {{ tools.unit }} </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
 </div>
 <div>
    <h2>
        <span class="recipe-name">
            Рецепт котетйля
        </span>
    </h2>
    <ol class="steps">
        {% for recipe in my_cocktail.cocktail_recipe %} 
        <li> {{ recipe.recipe }}</li>
        {% endfor %}
    </ol>
 </div>

    
</body>