webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Панель управления'
    return render_template('admin/index.html', page_title=title)

webapp/cocktails/views.py
from flask import Blueprint, render_template, redirect, url_for
from sqlalchemy.sql.expression import func
from webapp.cocktails.models import Cocktails, Tags
from webapp.user.forms import SearchForm
from webapp import db


blueprint = Blueprint('cocktail', __name__)


@blueprint.route('/')
def index():
    page_title = 'Home-barman'
    cocktails = Cocktails.query.order_by(func.random()).limit(12).all()
    return render_template('index.html', page_title=page_title, cocktails=cocktails)


@blueprint.route('/recipe')
def recipe():
    return render_template('recipe.html')

@blueprint.route('/cocktail/<int:cocktail_id>')
def single_cocktail(cocktail_id):
    my_cocktail = Cocktails.query.filter(Cocktails.id == cocktail_id).first()
    return render_template('cocktails/single_cocktail.html', page_title=my_cocktail.title,
                            my_cocktail=my_cocktail)


@blueprint.context_processor
def base():
    form = SearchForm()
    return dict(form=form)


@blueprint.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    cocktails = Cocktails.query
    if form.validate_on_submit():
        single_cocktail.searched = form.searched.data
        cocktails = cocktails.filter((Cocktails.tags.like('%' + single_cocktail.searched + '%') |
                                     (Cocktails.title.like('%' + single_cocktail.searched + '%'))))
        return render_template('cocktails/search.html', form=form,
                               searched=single_cocktail.searched, cocktails=cocktails)
    else:
        return redirect(url_for('cocktail.index'))

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user


from webapp.db import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('cocktail.index'))
    title = 'Авторизация'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    """Запускает проверку введенных данных для авторизации
    пользователя методом запроса POST
    """
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы успешно вошли на сайт')
            return redirect(url_for('cocktail.index'))

    flash('Неправильное имя или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно зарегестрировались')
    return redirect(url_for('cocktail.index'))


@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('cocktail.index'))
    title = 'Регистрация'
    form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=form)


@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Вы успешно зарегестрировались')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле {}: {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(url_for('user.register'))

webapp/templates/base.html
 <!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Home-barman</title>
</head>
<!-- Fixed navbar -->
      {% include 'menu.html' %}
<body>
  <br/>
  <div class="container">
    {% include 'cocktails/cocktails.html' %}
  </div>  


</body>
</html>

webapp/templates/index.html
{% extends 'base.html' %}

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container">
    <h1>{{ page_title }}</h1>
    <div class="row">
        <div class ="col-4">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
              		{% for message in messages %}
                  		{{ message }}<br>
              		{% endfor %}
          		</div>
          		{% endif %}
      		{% endwith %}
            <form action="{{ url_for('user.process_login') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}<br>
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}<br>
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_='form-check-label') }}
                </div>    
                {{ form.submit }}
            </form>
        </div>
        <div class="col-8">

        </div>
    </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Home-Barman</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Главная страница</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('cocktail.recipe') }}">Добавить рецепт (в работе)</a>
            </li>
        </ul>        
        <form method= 'POST' action="{{ url_for('cocktail.search') }}" class="d-flex">
            {{ form.hidden_tag() }}
            <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="searched">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
        </form>
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">Привет, {{ current_user.username }}!</span>
                </li>
                {% if current_user.is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
                </li>    
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>    
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">Регистрация</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>
            {% endif %}
        </ul>  
      </div>
    </div>
  </nav>

webapp/templates/recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>
 
    <div class="container">
     
        <form class="row g-3 needs-validation" novalidate>
          <div class="col-md-4">
            <label  name ="author" id="title" class="form-control">Имя автора</label>
            <input type="text" class="form-control" id="validationCustom01" required>
            <div class="valid-feedback">
              Looks good!
            </div>
          </div>
          <div class="col-md-4">
            <label for="validationCustom02" name ="" class="form-control">Название рецепта</label>
            <input type="text" class="form-control" id="validationCustom02" required>
            <div class="valid-feedback">
              Looks good!
            </div>
          </div>
          <div class="col-md-4">
            
            
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Ингредиенты</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
          </div>
          <div class="col-12">
            <button class="btn btn-primary" type="submit">Отправить</button>
          </div>
          
     
        <a href="/" class="btn btn-primary my-2 , col-md-2">Назад</a>
       
      </div>
        
</body>
</html>